version: 2
jobs:
  build:
    docker:
    - image: circleci/mysql:5.7
    working_directory: /root/singnet
    environment:
      PYTHONPATH: /root/singnet/snet-marketplace-service
    steps:
    - run:
        name: Install Python and Git
        command: |
          mysql --version
          service mysql start
          apt-get update
          apt-get -y install sudo wget git
          apt-get -y install python3 python3-pip
    - run:
        name: Build and Test marketplace
        command: |
          git clone https://github.com/prashantramangupta/snet-marketplace-service.git
          cd snet-marketplace-service
          #mysql -h localhost -u root < ./test/unittest_db.sql
          #pip3 install -r requirement.txt
          #export PYTHONPATH=$PATH:/root/singnet/snet-marketplace-service
          #cp ./test/constant.py ./common/constant.py
          #cp ./test/.coveragerc ./
          #pip3 install coveralls
          #coverage run --source=/root/singnet/snet-marketplace-service ./test/test_contract_api.py
          #COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} coveralls
