---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-node
      - image: circleci/mysql:8.0.4
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_PASSWORD: unittest_pwd
          MYSQL_DATABASE: unittest_db
          MYSQL_USER: unittest_root
          MYSQL_PASSWORD: unittest_pwd
    working_directory: ~/singnet
    steps:
      - checkout
      - run:
          name: generating checksum for all requirements file
          command: |
            shasum */requirement*.txt > /tmp/checksum_files_list
            sudo chmod 777 -R /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: dependency-cache-{{ checksum "/tmp/checksum_files_list" }}
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install required packages.
          command: |
            sudo apt-get update
            sudo apt-get install mysql-client -y
            sudo pip install coverage coveralls pytest boto3
      - run:
          name: Install dependencies
          command: |
            for requirement_file in `ls */requirement*.txt`;do sudo pip install -r $requirement_file --prefer-binary ;done
      - run:
          name: Run tests for signer & wallets
          command: |
            #sudo pip install -r signer/requirement.txt
            PYTHONPATH=$PWD coverage run -m pytest signer/tests/test_signer.py wallets/testcase/unit_testcases/test_wallet_service.py
            coverage report -m
      - save_cache:
          key: dependency-cache-{{ checksum "/tmp/checksum_files_list" }}
          paths:
            - /usr/local/lib/python3.6/site-packages
