name: tests
on:
  # push:
  #   branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
    run_tests:
      runs-on: ubuntu-latest
      container: node:20-bookworm
      services:
        nginx:
          image: mysql:8.0.21
          env:
            MYSQL_ROOT_PASSWORD: unittest_pwd
            MYSQL_HOST: '%'
            MYSQL_DATABASE: unittest_db
            MYSQL_USER: unittest_root
            MYSQL_PASSWORD: unittest_pwd
            
      steps:
      - name: install pip
        run: |
          apt update
          apt install -y python3-pip python3.11-venv netcat-traditional
          
      - name: install packs
        run: |
          export PIP_BREAK_SYSTEM_PACKAGES=1
          apt install -y python3-pip python3.11-venv
          apt update --allow-releaseinfo-change
          apt install unzip -y
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip
          apt install default-mysql-client -y
          pip3 install coverage coveralls pytest alembic

      - name: clone repo
        uses: actions/checkout@v3

      - name: clone repo
        run: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
            
      - name: install packs
        run: |
          export PIP_BREAK_SYSTEM_PACKAGES=1
          mysql -h 127.0.0.1 -u root -punittest_pwd -e "create database registry_unittest_db"
          mysql -h 127.0.0.1 -u root -punittest_pwd -e "create database verification_unittest_db"
          mysql -h 127.0.0.1 -u root -punittest_pwd -e "GRANT ALL PRIVILEGES ON *.* TO 'unittest_root'@'%';"
          export PYTHONPATH=$PWD
          for alembic_file in `ls */alembic*.ini | cut -d '/' -f1`;do cd $alembic_file; echo $alembic_file; alembic upgrade head; cd .. ;done
          mysql -h 127.0.0.1 -u unittest_root -punittest_pwd unittest_db < orchestrator/testcases/script.sql
          
      - name: install required packages
        run: |
          export PIP_BREAK_SYSTEM_PACKAGES=1
          export CFLAGS="-I${PREFIX}/include/python3.11/cpython"
          for requirement_file in `ls */*/requirement*.txt`;do pip3 install -r $requirement_file ;done
          for requirement_file in `ls */requirement*.txt`;do pip3 install -r $requirement_file ;done
          for package_file in `ls */package*.json | cut -d '/' -f1`;do npm install $package_file/;done
      

